<div class="current-page" id="home">

	<section class="full-height" id="welcome">
		<h1>This is Mélodie's portfolio</h1>
		<p class="catch">I'm just a human trying to make sensory interfaces.</p>
	</section>

	<section class="full-height" id="my-job">
		<h2>My job</h2>
		<p class="catch">At <a href="www.user.io" target="_blank">User Studio</a>, I orchestrate and design stupendous projects</p>
		<p>I'm UX/UI Designer and Lead project<br/>
			<a href="http://www.linkedin.com/in/melodiemancipoz"
			target="_blank">Show my Linked In profile</a>
		</p>
	</section>
		
	<section class="full-height project">
		<h2>Work</h2>
		<p class="catch">Imagine that you'll never forget anything anymore</p>
		<p>Connected&nbsp;object | Mobile&nbsp;app | UX/UI&nbsp;Design</p>
		<div class="img-wrapper">
			<img src="assets/img/projects/mindy-my-list.png"
			alt="mindy never my objects" />
		</div>
	</section>
	
	<section class="full-height project">
		<h2>Work</h2>
		<p class="catch">Imagine the sweetest way to wake up</p>
		<p>Connected&nbsp;object | Mobile&nbsp;app | UX/UI&nbsp;Design</p>
	</section>
	
	<section class="full-height">
		<h2>When i'm not designing or developping…</h2>
		<p class="catch">I hurtling down Paris with my longboard or mountains with my snowboard.</p>
	</section>
	
	<div class="radial-gradient" id="last-section">full</div>
	
	<div class="scroll-btn">
		<p data-icon="&#xe000;"></p>
	</div>
	
</div>